config/routes.rb
Rails.application.routes.draw do
  resources :recus
  resources :envoyes
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moncourriel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/@jarstone/dselect/dist/css/dselect.css">
    <script src="https://unpkg.com/@jarstone/dselect/dist/js/dselect.js"></script>

  </head>

  <body>   
    <div class="container-fluid">
      <div class="row flex-nowrap">
        <div class="col-auto col-md-2 col-xl-2 px-sm-2 px-0 sidebar-dark">
          <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
              <li class="nav-item">
                <%= link_to new_envoye_path, class: "nav-link align-middle #{request.original_fullpath.include?('/envoyes/new') ? 'active' : ''}" do %>
                  <i class="bi bi-plus-lg"></i>
                  <span class="ms-1 d-none d-sm-inline">Nouveau message</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to recus_path, class: "nav-link align-middle #{(request.original_fullpath == '/recus' or request.original_fullpath.include?('/recus/')) ? 'active' : ''}" do %>
                  <i class="bi bi-inbox-fill"></i>
                  <span class="ms-1 d-none d-sm-inline">Boîte de réception <%= @nb_non_lu > 0 ? "(#{@nb_non_lu})" : '' %></span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to envoyes_path, class: "nav-link align-middle #{(request.original_fullpath == '/envoyes' or request.original_fullpath.include?('/envoyes/') and !request.original_fullpath.include?('/envoyes/new')) ? 'active' : ''}" do %>
                  <i class="bi bi-send-fill"></i>
                  <span class="ms-1 d-none d-sm-inline">Messages envoyés</span>
                <% end %>
              </li>
              <li class="nav-item ">
                <%= link_to envoyes_path(brouillon: true), class: "nav-link align-middle #{request.original_fullpath.include?('/envoyes?brouillon=true') ? 'active' : ''}" do %>
                  <i class="bi bi-pencil-fill"></i>
                  <span class="ms-1 d-none d-sm-inline">Brouillon</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to recus_path(corbeille: true), class: "nav-link align-middle #{request.original_fullpath == '/recus?corbeille=true' ? 'active' : ''}" do %>
                  <i class="bi bi-trash-fill"></i>
                  <span class="ms-1 d-none d-sm-inline">Corbeille</span>
                <% end %>
              </li>
            </ul>
            <%= User.find(@current_user_id).nom_complet %>
          </div>
        </div>
      
        <div class="col py-3 central">
          <%= yield %>
        </div>

      </div>
    </div>
    
  </body>
</html>